// Actions regarding the user
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const GET_USER_LEVEL_INFO_START = 'GET_USER_LEVEL_INFO_START';
export const GET_USER_LEVEL_INFO_END = 'GET_USER_LEVEL_INFO_END';
export const GET_USER_LEVEL_INFO_ERROR = 'GET_USER_LEVEL_INFO_ERROR';
export const GET_USER_INFO_START = 'GET_USER_INFO_START';
export const GET_USER_INFO_END = 'GET_USER_INFO_END';
export const GET_USER_INFO_ERROR = 'GET_USER_INFO_ERROR';

// Actions regarding the Javagochi races
export const REQUEST_JC_RACES = 'REQUEST_JC_RACES';
export const REQUEST_JC_RACE = 'REQUEST_JC_RACE';
export const RECEIVED_JC_RACES = 'RECEIVED_JC_RACES';
export const RECEIVED_JC_RACE = 'RECEIVED_JC_RACE';
export const JC_RACES_FAILED = 'JC_RACES_FAILED';
export const JC_RACE_FAILED = 'JC_RACE_FAILED';
export const JC_BUY_START = 'JC_BUY_START';
export const JC_BUY_END = 'JC_BUY_END';
export const JC_BUY_FAIL = 'JC_BUY_FAIL';

// Actions regarding the Javagochi owned
export const REQUEST_OWNED_JCS = 'REQUEST_OWNED_JCS';
export const RECEIVED_OWNED_JCS = 'RECEIVED_OWNED_JCS';
export const JC_OWNED_FAILED = 'JC_OWNED_FAILED';
export const GET_JC_LEVEL_INFO_START = 'GET_JC_LEVEL_INFO_START';
export const GET_JC_LEVEL_INFO_END = 'GET_JC_LEVEL_INFO_END';
export const GET_JC_LEVEL_INFO_ERROR = 'GET_JC_LEVEL_INFO_ERROR';
export const REQUEST_OWNED_JC_BY_ID = 'REQUEST_OWNED_JCS_BY_ID';
export const RECEIVED_OWNED_JC_BY_ID = 'RECEIVED_OWNED_JC_BY_ID';

// Actions regarding the trades
export const REQUEST_ALL_TRADES = 'REQUEST_ALL_TRADES';
export const RECEIVED_ALL_TRADES = 'RECEIVED_ALL_TRADES';
export const ALL_TRADES_FAIL = 'ALL_TRADES_FAIL';
export const REQUEST_USER_TRADES = 'REQUEST_USER_TRADES';
export const RECEIVED_USER_TRADES = 'RECEIVED_USER_TRADES';
export const USER_TRADES_FAIL = 'USER_TRADES_FAIL';
export const ADD_TRADE_START = 'ADD_TRADE_START';
export const ADD_TRADE_END = 'ADD_TRADE_END';
export const ADD_TRADE_FAIL = 'ADD_TRADE_FAIL';

// Actions regarding items
export const REQUEST_ITEMS = 'REQUEST_ITEMS';
export const REQUEST_ITEM_DETAIL = 'REQUEST_ITEM_DETAIL';
export const RECEIVED_ITEMS = 'RECEIVED_ITEMS';
export const RECEIVED_ITEM_DETAIL = 'RECEIVED_ITEM_DETAIL';
export const ITEMS_FAILED = 'ITEMS_FAILED';
export const ITEM_DETAIL_FAILED = 'ITEM_DETAIL_FAILED';
export const ITEM_BUY_START = 'ITEM_BUY_START';
export const ITEM_BUY_END = 'ITEM_BUY_END';
export const ITEM_BUY_FAIL = 'ITEM_BUY_FAIL';

// Actions regarding owned items
export const REQUEST_USER_ITEMS = 'REQUEST_USER_ITEMS';
export const REQUEST_USER_ITEM_DETAIL = 'REQUEST_USER_ITEM_DETAIL';
export const RECEIVED_USER_ITEMS = 'RECEIVED_USER_ITEMS';
export const RECEIVED_USER_ITEM_DETAIL = 'RECEIVED_USER_ITEM_DETAIL';
export const OWNED_ITEMS_FAIL = 'OWNED_ITEMS_FAIL';
export const OWNED_ITEM_DETAIL_FAIL = 'OWNED_ITEM_DETAIL_FAIL';
export const USE_ITEM_START = 'USE_ITEM_START';
export const USE_ITEM_END = 'USE_ITEM_END';
export const USE_ITEM_ERROR = 'USE_ITEM_ERROR';
export const USE_ITEM = 'USE_ITEM';
